export const MESSAGES = {
    CHANGE_URL: 'CHANGE_URL',
    CHANGE_CHAPTER: 'CHANGE_CHAPTER',
    CHANGE_ACTIVE_ICON: 'CHANGE_ACTIVE_ICON',
    CHANGE_ACTIVE_TAB: 'CHANGE_ACTIVE_TAB',
    CHANGE_ICON_TEXT: 'CHANGE_ICON_TEXT',
};

export const COMMANDS = {
    NEXT_CHAPTER: 'ycs-forward',
    PREV_CHAPTER: 'ycs-back',
};
